spring :
  application :
    name : eureka-server
server :
  port : 8761
  waitTimeInMsWhenSyncEmpty: 0

eureka :
  instance :
    hostname : eureka-server
    prefer-ip-address : true
  client :
    register-with-eureka : false
    fetch-registry : false
    serviceUrl :
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
