server :
  port : 9191

spring :
  application :
    name : API-GATEWAY
  cloud :
    gateway :
      routes :
        - id : USER-SERVICE
          uri : lb://USER-SERVICE
          predicates :
            - Path=/users/**
          filter:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallbackMethod

        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filter :
            - name : CircuitBreaker
              args :
                name : DEPARTMENT-SERVICE
                fallbackuri : forward:/deptServiceFallbackMethod

