version: '2.1'
services :
  eureka-server :
    image : vt-service-registry:0.0.1-SNAPSHOT
    ports :
      - "8761:8761"
    hostname : eureka-server
    networks :
       backend :
          aliases:
             - "eurekaserver"

  config-server :
    image : vt-cloud-config:0.0.1-SNAPSHOT
    ports:
      - "9296:9296"
    links :
      - eureka-server
    networks:
      backend:
        aliases:
          - "configserver"

  department-service :
    image : vt-department-service:0.0.1-SNAPSHOT
    ports :
      - "9023:9023"
    hostname : department-service
    depends_on :
      config-server :
        condition: service_started
    networks:
       backend:
            aliases:
               - "departmentserivce"
  user-service:
    image: vt-user-service:0.0.1-SNAPSHOT
    ports:
      - "9024:9024"
    hostname: user-service
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "userserivce"
  cloud-gateway:
    image: vt-cloud-gateway:0.0.1-SNAPSHOT
    ports:
      - "9191:9191"
    hostname: cloud-gateway
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "cloudgatewayserivce"

networks:
  backend:
    driver: bridge