version: '2.1'
services :
  eureka-server :
    image : service-registry:0.0.1-SNAPSHOT
    ports :
      - "8761:8761"
    networks :
       backend :
          aliases:
             - "eurekaserver"

  config-server :
    image : cloud-config
    ports:
      - "9296:9296"
    networks:
      backend:
        aliases:
          - "configserver"


networks:
  backend:
    driver: bridge