version: '3'
services :
  eureka-server :
    image : vt-service-registry:0.0.1-SNAPSHOT
    ports :
      - "8761:8761"
    hostname : eureka-server
    links:
      - config
    networks :
       backend :
          aliases:
             - "eurekaserver"

  config-server :
    image : vt-cloud-config:0.0.1-SNAPSHOT
    ports:
      - "9296:9296"
    networks:
      backend:
        aliases:
          - "configserver"

  department-service :
    image : vt-department-service:0.0.1-SNAPSHOT
    ports :
      - "9023:9023"
    hostname : department-service
    links :
      - config-server
    networks:
       backend:
            aliases:
               - "departmentserivce"

networks:
  backend:
    driver: bridge